### ISSUE TITLE
如何下载该程序？ 只有两张图片和一个 "读我 "文件

### ISSUE THREAD

**Issue by Mustafarexdo** [DNNDHH/FGO-cmd#4]
如何下载程序？ 只有两张图片和一个自述文件，如何访问和使用程序？

**Comment by Zhen-Bo** [comment]
這個公開專案估計只是大老在軍火展示, 順便幫你指路跟你說有這個東西可以讓你自己去修改實作以符合當前版本
實際上更新的部分與新的 UI 估計都儲存於人家電腦的 local branch 或是他的私人專案內

畢竟這種脫機的東西越少人用越好, 太多人不考慮原理無腦用就有可能被官方發現然後直接封號,
最活生生的例子你直接搜 "BGO 脫機" 就會看到 3000 多個帳號就有可能引起官方關注
想要限制人數對於當前一堆伸手黨小白最有效的方法是啥? 就是提高入門門檻
真想搞的話可以去 [hexstr大老的原專案](https://github.com/hexstr/FateBot/) 修改並編譯執行

原語言是 C 語言, 不過應該也可以轉換成比較容易上手的 python
最近才剛重構完 hexstr 大老的自動登入,  以前第一次發現的時候想要多改一些功能 (大約22年聖誕節前)
想說大老的 code 應該很好修改吧, 點開源碼一看, 沒想到大老直接拉了一坨大, 當場直接放棄不改了
~~PS:其實當時也有改一版 server 版本的 (db+docker執行), 而不是用 workflow 跑~~
也挺佩服 O-Isaac 跟 DNNDHH 兩位大老可以直接在原版本上做修改而去忽略這代碼的味道, 只能說大老的世界我不懂

**Comment by DNNDHH** [comment]
Fatebot都开源了…你去抄一下不就好了…加解密计算啥么都有了～根本不用想这是怎么计算的这种问题…复制粘贴就行的事😅
https://github.com/hexstr/FateBot
就按自己喜欢的风格做了一个就行…这种东西发成品出来传得很快…太恶劣了运营注意到就会开始处理！
今年2月开始就加个强制uuid签名验证就恶心到了！整得还断签几天，现在彻底启用了签名验证…(有据说是Aniplex方面要求的…但我觉得是运营多少开始在意这些脱机程序的泛滥)



我这个开始做的时候…什么都没有…很多功能就是hexstr大佬的…当时Fatebot还没开源，他在tg给我看了加解密方式计算方法的源码参考了一下，最后就是加解密的key和iv是Neo大佬给我的…他不知道我做的是外挂…他知道可能就生气了！所以我不打算发出来…就开个库…让大家知道有这个东西就行！

后来…hexstr大佬把Fatebot开源了😅
