### ISSUE TITLE
大佬能做个自定义抽卡吗。

### ISSUE THREAD

**Issue by aabb12a** [DNNDHH/FGO-cmd#5]
就是做个能抽卡的程序，有偿也行.

**Comment by DNNDHH** [comment]
🤔这个好像没啥用吧…除了可以搞客户端没有的护符十连抽卡…其它都不能改…包括强制保底回传…服务器都不认

**Comment by aabb12a** [comment]
您理解错了，我是想要客户端抽卡的，能护肤和十连的。

**Comment by aabb12a** [comment]
![665](https://github.com/DNNDHH/FGO-cmd/assets/171225355/ae19e300-7b2f-45fd-8bf2-4eb588581d09)
就是这个功能

**Comment by DNNDHH** [comment]
> ![665](https://github.com/DNNDHH/FGO-cmd/assets/171225355/ae19e300-7b2f-45fd-8bf2-4eb588581d09)
> 就是这个功能

这个啊…我改天单独做一个发出来吧

**Comment by aabb12a** [comment]
![665](https://github.com/DNNDHH/FGO-cmd/assets/171225355/23be5c61-6a11-4d2c-b9fe-d6285f70dc33)


> > ![665](https://private-user-images.githubusercontent.com/171225355/347488775-ae19e300-7b2f-45fd-8bf2-4eb588581d09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MzcxMDksIm5iZiI6MTcyMDYzNjgwOSwicGF0aCI6Ii8xNzEyMjUzNTUvMzQ3NDg4Nzc1LWFlMTllMzAwLTdiMmYtNDVmZC04YmYyLTRlYjU4ODU4MWQwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQxODQwMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDlmMDdiZjY5ZTNmMmQyMTdjNTUxY2MzZWI0YWE5Zjg0ZWEzYmRlMWMyZTI2ZGFiOTc2YmJlYjJlNGY1NzhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xe_Rw_GDDrHKi3PIpMoEPxQeznL3xOIVpzLjSRlitjc)
> > 就是这个功能
> 
> 这个啊……我单独和你们谈一天提出来吧

谢谢大佬，Thanks♪(･ω･)ﾉ。

**Comment by aabb12a** [comment]
大佬咕咕咕了吗😁



---- 回复的原邮件 ----
| 发件人 | Nasu Ni ***@***.***> |
| 日期 | 2024年07月11日 02:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [DNNDHH/FGO-cmd] 大佬能做个自定义抽卡吗。 (Issue #5) |

665.png (view on web)
就是这个功能

这个啊…我改天单独做一个发出来吧

**Comment by aabb12a** [comment]
大佬软件好了吗，还是需要私下付费才能下载吗。
